"""Generated human-readable portfolio dashboard (US-001).

The dashboard is derived output: it is regenerated from the registry and the
snapshot, and nothing reads it back. Every GitHub-derived section states how old
its evidence is.
"""

from __future__ import annotations

import datetime as dt
from typing import Any

from .github.snapshot import Snapshot, humanize_age
from .model import Lifecycle, Project
from .queries import (
    build_review_queue,
    build_work_queue,
    find_missing_next_actions,
    list_open_prs,
    signal_ref,
)
from .signals import SignalConfig, build_attention_queue, find_mismatches
from .storage import Registry
from .validation import ERROR, ValidationReport, validate

BANNER = "<!-- Generated by `registry dashboard`. Edit registry/projects/*.yaml, not this file. -->"


def render_dashboard(
    registry: Registry,
    snapshot: Snapshot | None = None,
    now: dt.datetime | None = None,
    report: ValidationReport | None = None,
    config: SignalConfig | None = None,
) -> str:
    now = now or dt.datetime.now(dt.timezone.utc)
    snapshot = snapshot or Snapshot()
    report = report or validate(registry, today=now.date())

    lines: list[str] = [
        "# Portfolio Dashboard",
        "",
        BANNER,
        "",
        f"Generated {now.strftime('%Y-%m-%d %H:%M UTC')} · "
        f"{len(registry)} project{'' if len(registry) == 1 else 's'} · "
        f"GitHub evidence {humanize_age(snapshot.fetched_at, now)}"
        + (" (stale)" if snapshot.is_stale(now) else ""),
        "",
    ]

    lines += _health_section(report)
    lines += _lifecycle_section(registry)
    lines += _active_section(registry, now)
    lines += _work_queue_section(registry, snapshot, now, config)
    lines += _missing_next_actions_section(registry)
    lines += _prs_section(registry, snapshot, now)
    lines += _attention_section(registry, snapshot, now, config)
    lines += _mismatch_section(registry, snapshot, now, config)
    lines += _review_queue_section(registry, snapshot, now)
    lines += _accomplishments_section(registry)
    lines += _relationships_section(registry)

    return "\n".join(lines).rstrip() + "\n"


def _heading(title: str, count: int | None = None) -> list[str]:
    suffix = f" ({count})" if count is not None else ""
    return [f"## {title}{suffix}", ""]


def _empty(message: str) -> list[str]:
    return [f"_{message}_", ""]


def _health_section(report: ValidationReport) -> list[str]:
    lines = _heading("Registry health")
    if report.ok and not report.suggestions:
        return lines + _empty("All checks pass.")
    lines.append(
        f"- **{len(report.errors)} errors**, {len(report.suggestions)} suggestions"
    )
    for finding in report.errors[:10]:
        where = f"`{finding.project_id}` — " if finding.project_id else ""
        lines.append(f"  - {where}{finding.message} (`{finding.rule_id}`)")
    if len(report.errors) > 10:
        lines.append(f"  - …and {len(report.errors) - 10} more; run `registry validate`")
    lines.append("")
    return lines


def _lifecycle_section(registry: Registry) -> list[str]:
    lines = _heading("Lifecycle")
    counts = {lc: 0 for lc in Lifecycle}
    for project in registry:
        counts[project.lifecycle] += 1
    lines.append("| Lifecycle | Projects | Active |")
    lines.append("|---|---:|---:|")
    for lifecycle in Lifecycle:
        active = sum(
            1 for p in registry if p.lifecycle is lifecycle and p.active
        )
        lines.append(f"| `{lifecycle.value}` | {counts[lifecycle]} | {active} |")
    lines.append("")
    return lines


def _active_section(registry: Registry, now: dt.datetime) -> list[str]:
    active = [p for p in registry if p.active]
    lines = _heading("Active projects", len(active))
    if not active:
        return lines + _empty("Nothing is marked active.")
    lines.append("| Project | Lifecycle | Priority | Next action | Reviewed |")
    lines.append("|---|---|---|---|---|")
    for project in active:
        action = project.next_action.description if project.next_action else "**— none —**"
        reviewed = (
            project.last_reviewed.isoformat() if project.last_reviewed else "never"
        )
        priority = project.priority.value if project.priority else "—"
        lines.append(
            f"| {_project_link(project)} | `{project.lifecycle.value}` | {priority} "
            f"| {action} | {reviewed} |"
        )
    lines.append("")
    return lines


def _work_queue_section(
    registry: Registry, snapshot: Snapshot, now: dt.datetime, config: SignalConfig | None
) -> list[str]:
    queue = build_work_queue(registry, snapshot, now=now, config=config)[:12]
    lines = _heading("Work queue")
    if not queue:
        return lines + _empty("Nothing queued.")
    lines.append("| Item | Project | Human priority | GitHub urgency | Why |")
    lines.append("|---|---|---|---|---|")
    for item in queue:
        priority = item.human_priority or "not recorded"
        why = "; ".join(item.reasons[:2])
        project = item.project_id or "—"
        lines.append(
            f"| {_truncate(item.title, 60)} | {project} | {priority} "
            f"| {item.github_urgency} | {_truncate(why, 80)} |"
        )
    lines.append("")
    return lines


def _missing_next_actions_section(registry: Registry) -> list[str]:
    missing = find_missing_next_actions(registry)
    lines = _heading("Missing next actions", len(missing))
    if not missing:
        return lines + _empty("Every active project has a next action.")
    for row in missing:
        lines.append(f"- `{row['project_id']}` — {row['reason']}")
    lines.append("")
    return lines


def _prs_section(registry: Registry, snapshot: Snapshot, now: dt.datetime) -> list[str]:
    result = list_open_prs(snapshot, registry, now=now)
    rows = result["pull_requests"]
    lines = _heading("Open pull requests", len(rows))
    lines.append(f"_Evidence fetched {result['age']}" + (" — stale_" if result["stale"] else "_"))
    lines.append("")
    if not rows:
        return lines + _empty("No open pull requests in the last snapshot.")
    lines.append("| PR | Title | Draft | Age | Review | CI |")
    lines.append("|---|---|---|---:|---|---|")
    for row in rows[:20]:
        link = f"[{row['repo']}#{row['number']}]({row['url']})" if row["url"] else \
            f"{row['repo']}#{row['number']}"
        lines.append(
            f"| {link} | {_truncate(row['title'], 50)} | {'yes' if row['draft'] else 'no'} "
            f"| {row['age_days']}d | {row['review_state']} | {row['ci_state']} |"
        )
    lines.append("")
    return lines


def _attention_section(
    registry: Registry, snapshot: Snapshot, now: dt.datetime, config: SignalConfig | None
) -> list[str]:
    items = build_attention_queue(registry, snapshot, now=now, config=config)
    lines = _heading("Needs attention", len(items))
    if not items:
        return lines + _empty("No attention signals in the last snapshot.")
    for item in items[:15]:
        ref = signal_ref(item.repo, item.number)
        link = f"[{ref}]({item.url})" if item.url else ref
        lines.append(
            f"- **{item.severity}** {link} — {item.reason} (`{item.rule_id}`)"
        )
    lines.append("")
    return lines


def _mismatch_section(
    registry: Registry, snapshot: Snapshot, now: dt.datetime, config: SignalConfig | None
) -> list[str]:
    mismatches = find_mismatches(registry, snapshot, now=now, config=config)
    lines = _heading("Registry / GitHub mismatches", len(mismatches))
    if not mismatches:
        return lines + _empty("Registry intent and GitHub state agree.")
    for mismatch in mismatches[:15]:
        marker = "**error**" if mismatch.severity == ERROR else "suggestion"
        lines.append(
            f"- {marker} `{mismatch.project_id}` — {mismatch.message} (`{mismatch.rule_id}`)"
        )
    lines.append("")
    return lines


def _review_queue_section(
    registry: Registry, snapshot: Snapshot, now: dt.datetime
) -> list[str]:
    queue = build_review_queue(registry, snapshot, now=now)
    lines = _heading("Review queue", len(queue))
    if not queue:
        return lines + _empty("Nothing is due for review.")
    for item in queue[:15]:
        lines.append(
            f"- `{item.project_id}` (`{item.lifecycle}`) — {'; '.join(item.reasons)}"
        )
    lines.append("")
    return lines


def _accomplishments_section(registry: Registry) -> list[str]:
    recent: list[tuple[Any, Project]] = [
        (a, p) for p in registry for a in p.accomplishments
    ]
    recent.sort(key=lambda pair: pair[0].date, reverse=True)
    lines = _heading("Recent accomplishments")
    if not recent:
        return lines + _empty("No accomplishments recorded yet.")
    for accomplishment, project in recent[:10]:
        lines.append(
            f"- {accomplishment.date.isoformat()} — **{project.name}**: "
            f"{accomplishment.summary} (`{accomplishment.kind.value}`)"
        )
    lines.append("")
    return lines


def _relationships_section(registry: Registry) -> list[str]:
    edges = [(p, r) for p in registry for r in p.relationships]
    lines = _heading("Relationships", len(edges))
    if not edges:
        return lines + _empty("No relationships recorded.")
    for project, relationship in edges:
        note = f" — {relationship.note}" if relationship.note else ""
        lines.append(
            f"- `{project.id}` → **{relationship.kind.value}** → "
            f"`{relationship.target}`{note}"
        )
    lines.append("")
    return lines


def _project_link(project: Project) -> str:
    if project.repo:
        return f"[{project.name}](https://github.com/{project.repo})"
    return project.name


def _truncate(text: str, limit: int) -> str:
    text = text.replace("|", "\\|").replace("\n", " ")
    return text if len(text) <= limit else text[: limit - 1] + "…"
